//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedbackTracker.Common.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListWebHook
    {
        public System.Guid Id { get; set; }
        public System.Guid ListId { get; set; }
        public string LastChangeToken { get; set; }
        public string StartingUrl { get; set; }
    }
}
